/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasosIndexRouteImport } from './routes/casos.index'
import { Route as CasosCaseIdRouteImport } from './routes/casos.$caseId'

const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosIndexRoute = CasosIndexRouteImport.update({
  id: '/casos/',
  path: '/casos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosCaseIdRoute = CasosCaseIdRouteImport.update({
  id: '/casos/$caseId',
  path: '/casos/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/onboarding': typeof OnboardingRoute
  '/parceiros': typeof ParceirosRoute
  '/casos/$caseId': typeof CasosCaseIdRoute
  '/casos/': typeof CasosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/onboarding': typeof OnboardingRoute
  '/parceiros': typeof ParceirosRoute
  '/casos/$caseId': typeof CasosCaseIdRoute
  '/casos': typeof CasosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/onboarding': typeof OnboardingRoute
  '/parceiros': typeof ParceirosRoute
  '/casos/$caseId': typeof CasosCaseIdRoute
  '/casos/': typeof CasosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/onboarding'
    | '/parceiros'
    | '/casos/$caseId'
    | '/casos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/onboarding'
    | '/parceiros'
    | '/casos/$caseId'
    | '/casos'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/onboarding'
    | '/parceiros'
    | '/casos/$caseId'
    | '/casos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  OnboardingRoute: typeof OnboardingRoute
  ParceirosRoute: typeof ParceirosRoute
  CasosCaseIdRoute: typeof CasosCaseIdRoute
  CasosIndexRoute: typeof CasosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/': {
      id: '/casos/'
      path: '/casos'
      fullPath: '/casos/'
      preLoaderRoute: typeof CasosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/$caseId': {
      id: '/casos/$caseId'
      path: '/casos/$caseId'
      fullPath: '/casos/$caseId'
      preLoaderRoute: typeof CasosCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  OnboardingRoute: OnboardingRoute,
  ParceirosRoute: ParceirosRoute,
  CasosCaseIdRoute: CasosCaseIdRoute,
  CasosIndexRoute: CasosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
