// <auto-generated />
using System;
using DataPath.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable enable

namespace DataPath.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DataPathDbContext))]
    [Migration("20260728000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataPath.Core.Entities.AuditLog", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("Details")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<string>("EntityId")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("EntityName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("IpAddress")
                    .IsRequired()
                    .HasMaxLength(45)
                    .HasColumnType("character varying(45)");

                b.Property<DateTime>("Timestamp")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("NOW()");

                b.Property<string>("UserAgent")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<Guid?>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("Timestamp");

                b.HasIndex("UserId");

                b.HasIndex("EntityName", "EntityId");

                b.ToTable("audit_logs", (string)null);
            });

            modelBuilder.Entity("DataPath.Core.Entities.BiopsyCase", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<string>("ClinicalSummary")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("character varying(4000)");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("NOW()");

                b.Property<Guid>("CreatedByUserId")
                    .HasColumnType("uuid");

                b.Property<string>("InternalCaseCode")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("OrganSite")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<int?>("PatientAgeAtBiopsy")
                    .HasColumnType("integer");

                b.Property<string>("PatientBiologicalSex")
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)");

                b.Property<string>("StainingType")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("Status")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasDefaultValue("Pending");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("CreatedAt");

                b.HasIndex("CreatedByUserId");

                b.HasIndex("InternalCaseCode")
                    .IsUnique();

                b.HasIndex("OrganSite");

                b.HasIndex("Status");

                b.ToTable("biopsy_cases", (string)null);
            });

            modelBuilder.Entity("DataPath.Core.Entities.ClinicalOpinion", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<string>("AdditionalComments")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<Guid>("BiopsyCaseId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("NOW()");

                b.Property<string>("DiagnosticImpression")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("character varying(4000)");

                b.Property<bool>("IsSigned")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<Guid>("IssuedByUserId")
                    .HasColumnType("uuid");

                b.Property<string>("MicroscopicDescription")
                    .HasMaxLength(4000)
                    .HasColumnType("character varying(4000)");

                b.Property<string>("PriorityLevel")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<DateTime?>("SignedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("BiopsyCaseId");

                b.HasIndex("IssuedByUserId");

                b.ToTable("clinical_opinions", (string)null);
            });

            modelBuilder.Entity("DataPath.Core.Entities.SlideFile", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<Guid>("BiopsyCaseId")
                    .HasColumnType("uuid");

                b.Property<string>("ContentType")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("FileHash")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<long>("FileSizeBytes")
                    .HasColumnType("bigint");

                b.Property<string>("OriginalFileName")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTime?>("ShareLinkExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("StoragePath")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)");

                b.Property<string>("TemporaryShareLink")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<DateTime>("UploadedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("NOW()");

                b.HasKey("Id");

                b.HasIndex("BiopsyCaseId");

                b.ToTable("slide_files", (string)null);
            });

            modelBuilder.Entity("DataPath.Core.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("NOW()");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(254)
                    .HasColumnType("character varying(254)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<DateTime?>("LastLoginAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("ProfessionalRegistration")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("Specialty")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("users", (string)null);
            });

            modelBuilder.Entity("DataPath.Core.Entities.AuditLog", b =>
            {
                b.HasOne("DataPath.Core.Entities.User", "User")
                    .WithMany("AuditLogs")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("User");
            });

            modelBuilder.Entity("DataPath.Core.Entities.BiopsyCase", b =>
            {
                b.HasOne("DataPath.Core.Entities.User", "CreatedByUser")
                    .WithMany("CreatedCases")
                    .HasForeignKey("CreatedByUserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("CreatedByUser");
            });

            modelBuilder.Entity("DataPath.Core.Entities.ClinicalOpinion", b =>
            {
                b.HasOne("DataPath.Core.Entities.BiopsyCase", "BiopsyCase")
                    .WithMany("Opinions")
                    .HasForeignKey("BiopsyCaseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("DataPath.Core.Entities.User", "IssuedByUser")
                    .WithMany("IssuedOpinions")
                    .HasForeignKey("IssuedByUserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("BiopsyCase");

                b.Navigation("IssuedByUser");
            });

            modelBuilder.Entity("DataPath.Core.Entities.SlideFile", b =>
            {
                b.HasOne("DataPath.Core.Entities.BiopsyCase", "BiopsyCase")
                    .WithMany("SlideFiles")
                    .HasForeignKey("BiopsyCaseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("BiopsyCase");
            });

            modelBuilder.Entity("DataPath.Core.Entities.BiopsyCase", b =>
            {
                b.Navigation("Opinions");

                b.Navigation("SlideFiles");
            });

            modelBuilder.Entity("DataPath.Core.Entities.User", b =>
            {
                b.Navigation("AuditLogs");

                b.Navigation("CreatedCases");

                b.Navigation("IssuedOpinions");
            });
#pragma warning restore 612, 618
        }
    }
}
